/* tslint:disable */
/* eslint-disable */
/**
 * Monitor Proxy API
 * Basic API proxy for Monitor
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CheckResponseResult } from './CheckResponseResult';
import {
    CheckResponseResultFromJSON,
    CheckResponseResultFromJSONTyped,
    CheckResponseResultToJSON,
} from './CheckResponseResult';
import type { ErrorResult } from './ErrorResult';
import {
    ErrorResultFromJSON,
    ErrorResultFromJSONTyped,
    ErrorResultToJSON,
} from './ErrorResult';

/**
 * 
 * @export
 * @interface CheckResponse
 */
export interface CheckResponse {
    /**
     * 
     * @type {ErrorResult}
     * @memberof CheckResponse
     */
    error?: ErrorResult;
    /**
     * 
     * @type {CheckResponseResult}
     * @memberof CheckResponse
     */
    result?: CheckResponseResult;
}

/**
 * Check if a given object implements the CheckResponse interface.
 */
export function instanceOfCheckResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CheckResponseFromJSON(json: any): CheckResponse {
    return CheckResponseFromJSONTyped(json, false);
}

export function CheckResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : ErrorResultFromJSON(json['error']),
        'result': !exists(json, 'result') ? undefined : CheckResponseResultFromJSON(json['result']),
    };
}

export function CheckResponseToJSON(value?: CheckResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': ErrorResultToJSON(value.error),
        'result': CheckResponseResultToJSON(value.result),
    };
}

