/* tslint:disable */
/* eslint-disable */
/**
 * Monitor Proxy API
 * Basic API proxy for Monitor
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Check
 */
export interface Check {
    /**
     * 
     * @type {boolean}
     * @memberof Check
     */
    up?: boolean;
}

/**
 * Check if a given object implements the Check interface.
 */
export function instanceOfCheck(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CheckFromJSON(json: any): Check {
    return CheckFromJSONTyped(json, false);
}

export function CheckFromJSONTyped(json: any, ignoreDiscriminator: boolean): Check {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'up': !exists(json, 'up') ? undefined : json['up'],
    };
}

export function CheckToJSON(value?: Check | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'up': value.up,
    };
}

