/* tslint:disable */
/* eslint-disable */
/**
 * Monitor Proxy API
 * Basic API proxy for Monitor
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Site } from './Site';
import {
    SiteFromJSON,
    SiteFromJSONTyped,
    SiteToJSON,
} from './Site';

/**
 * 
 * @export
 * @interface SiteListResponse
 */
export interface SiteListResponse {
    /**
     * 
     * @type {Array<Site>}
     * @memberof SiteListResponse
     */
    sites: Array<Site>;
}

/**
 * Check if a given object implements the SiteListResponse interface.
 */
export function instanceOfSiteListResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "sites" in value;

    return isInstance;
}

export function SiteListResponseFromJSON(json: any): SiteListResponse {
    return SiteListResponseFromJSONTyped(json, false);
}

export function SiteListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteListResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sites': ((json['sites'] as Array<any>).map(SiteFromJSON)),
    };
}

export function SiteListResponseToJSON(value?: SiteListResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sites': ((value.sites as Array<any>).map(SiteToJSON)),
    };
}

