/* tslint:disable */
/* eslint-disable */
/**
 * Monitor Proxy API
 * basix API proxy for Monitor
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorResult } from './ErrorResult';
import {
    ErrorResultFromJSON,
    ErrorResultFromJSONTyped,
    ErrorResultToJSON,
} from './ErrorResult';
import type { SiteGetResponseResult } from './SiteGetResponseResult';
import {
    SiteGetResponseResultFromJSON,
    SiteGetResponseResultFromJSONTyped,
    SiteGetResponseResultToJSON,
} from './SiteGetResponseResult';

/**
 * 
 * @export
 * @interface SiteGetResponse
 */
export interface SiteGetResponse {
    /**
     * 
     * @type {ErrorResult}
     * @memberof SiteGetResponse
     */
    error?: ErrorResult;
    /**
     * 
     * @type {SiteGetResponseResult}
     * @memberof SiteGetResponse
     */
    result?: SiteGetResponseResult;
}

/**
 * Check if a given object implements the SiteGetResponse interface.
 */
export function instanceOfSiteGetResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SiteGetResponseFromJSON(json: any): SiteGetResponse {
    return SiteGetResponseFromJSONTyped(json, false);
}

export function SiteGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : ErrorResultFromJSON(json['error']),
        'result': !exists(json, 'result') ? undefined : SiteGetResponseResultFromJSON(json['result']),
    };
}

export function SiteGetResponseToJSON(value?: SiteGetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': ErrorResultToJSON(value.error),
        'result': SiteGetResponseResultToJSON(value.result),
    };
}

