/* tslint:disable */
/* eslint-disable */
/**
 * Monitor Proxy API
 * basix API proxy for Monitor
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorResult } from './ErrorResult';
import {
    ErrorResultFromJSON,
    ErrorResultFromJSONTyped,
    ErrorResultToJSON,
} from './ErrorResult';
import type { SiteAddResponseResult } from './SiteAddResponseResult';
import {
    SiteAddResponseResultFromJSON,
    SiteAddResponseResultFromJSONTyped,
    SiteAddResponseResultToJSON,
} from './SiteAddResponseResult';

/**
 * 
 * @export
 * @interface SiteAddResponse
 */
export interface SiteAddResponse {
    /**
     * 
     * @type {ErrorResult}
     * @memberof SiteAddResponse
     */
    error?: ErrorResult;
    /**
     * 
     * @type {SiteAddResponseResult}
     * @memberof SiteAddResponse
     */
    result?: SiteAddResponseResult;
}

/**
 * Check if a given object implements the SiteAddResponse interface.
 */
export function instanceOfSiteAddResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SiteAddResponseFromJSON(json: any): SiteAddResponse {
    return SiteAddResponseFromJSONTyped(json, false);
}

export function SiteAddResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteAddResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : ErrorResultFromJSON(json['error']),
        'result': !exists(json, 'result') ? undefined : SiteAddResponseResultFromJSON(json['result']),
    };
}

export function SiteAddResponseToJSON(value?: SiteAddResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': ErrorResultToJSON(value.error),
        'result': SiteAddResponseResultToJSON(value.result),
    };
}

