/* tslint:disable */
/* eslint-disable */
/**
 * Monitor Proxy API
 * basix API proxy for Monitor
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SiteAddRequest
 */
export interface SiteAddRequest {
    /**
     * 
     * @type {string}
     * @memberof SiteAddRequest
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof SiteAddRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the SiteAddRequest interface.
 */
export function instanceOfSiteAddRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function SiteAddRequestFromJSON(json: any): SiteAddRequest {
    return SiteAddRequestFromJSONTyped(json, false);
}

export function SiteAddRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteAddRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': json['url'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function SiteAddRequestToJSON(value?: SiteAddRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'name': value.name,
    };
}

