/* tslint:disable */
/* eslint-disable */
/**
 * Monitor Proxy API
 * Basic API proxy for Monitor
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Status } from './Status';
import {
    StatusFromJSON,
    StatusFromJSONTyped,
    StatusToJSON,
} from './Status';

/**
 * 
 * @export
 * @interface StatusResponseResult
 */
export interface StatusResponseResult {
    /**
     * 
     * @type {Status}
     * @memberof StatusResponseResult
     */
    status?: Status;
}

/**
 * Check if a given object implements the StatusResponseResult interface.
 */
export function instanceOfStatusResponseResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StatusResponseResultFromJSON(json: any): StatusResponseResult {
    return StatusResponseResultFromJSONTyped(json, false);
}

export function StatusResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusResponseResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : StatusFromJSON(json['status']),
    };
}

export function StatusResponseResultToJSON(value?: StatusResponseResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': StatusToJSON(value.status),
    };
}

