name: golangci-lint

on:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: extractions/setup-just@v1
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v3
        with:
          working-directory: apps/monitor-backend
          args: --timeout=5m
